AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  KoH_service_auth
  
  Sample SAM Template for KoH_service_auth

Parameters:
  Env:
    Type: String
    AllowedValues:
      - dev
      - prod
    Description: Environment in which the application will be deployed. Allowed values [dev, prod]

Globals:
  Function:
    Timeout: 5

Resources:
  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "KoH_${Env}_auth"
      CodeUri: ./
      Handler: main
      Runtime: go1.x
      Role: arn:aws:iam::763636035052:role/service-role/lambda-in-go-lang-executor
      Architectures:
        - x86_64
      Events:
        Auth:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            ApiId: !Ref HttpApi
            Path: /authenticate
            Method: POST
        VerifyToken:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            ApiId: !Ref HttpApi
            Path: /verify_token
            Method: GET
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
    Metadata:
      BuildMethod: makefile
  HttpApi:
      Type: AWS::Serverless::HttpApi
      Properties:
        StageName: !Ref Env
        # Tags:
        #   Tag: Value
        # AccessLogSettings:
        #   DestinationArn: !GetAtt AccessLogs.Arn
        #   Format: $context.requestId
        # DefaultRouteSettings:
        #   ThrottlingBurstLimit: 200
        # RouteSettings:
        #   "GET /path":
        #     ThrottlingBurstLimit: 500 # overridden in HttpApi Event
        # StageVariables:
        #   StageVar: Value
        # FailOnWarnings: true

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  AuthAPI:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/${Env}/"
  AuthFunction:
    Description: "KoH auth function"
    Value: !GetAtt AuthFunction.Arn
  # HelloWorldFunctionIamRole:
  #   Description: "Implicit IAM Role created for Hello World function"
  #   Value: !GetAtt HelloWorldFunctionRole.Arn
